// Bakes the print font into a source module.
//
//   node scripts/buildfont.mjs
//
// The PDF has to carry its own font: a reader will not have ours, and the
// standard fourteen have no Japanese at all. A whole CJK face is megabytes,
// so this asks Google Fonts for just the characters a refill can print and
// writes the result out as base64 for the bundler to pick up.
//
// Re-run it whenever CHARSET grows. Printing a character outside the set is
// the one thing this cannot survive, so the module exports the set too and
// the renderer checks against it.
import { writeFile } from 'node:fs/promises';

const ASCII = Array.from({ length: 95 }, (_, i) => String.fromCharCode(32 + i)).join('');
const KANA = [
  'ぁあぃいぅうぇえぉおかがきぎくぐけげこごさざしじすずせぜそぞただちぢっつづてでとど',
  'なにぬねのはばぱひびぴふぶぷへべぺほぼぽまみむめもゃやゅゆょよらりるれろゎわをん',
  'ァアィイゥウェエォオカガキギクグケゲコゴサザシジスズセゼソゾタダチヂッツヅテデトド',
  'ナニヌネノハバパヒビピフブプヘベペホボポマミムメモャヤュユョヨラリルレロヮワヲンヴ',
  'ーがぎぐげござじずぜぞだぢづでど・、。「」々',
].join('');
// Everything a part can print today, plus the labels the settings will reach
// for next: weekday and month names in Japanese, the six-day cycle, and the
// words the stamps are called by.
const KANJI = [
  '年月日曜週末始終',
  '先勝友引負仏滅大安赤口',          // 六曜
  '睦如弥生卯皐水無文葉長神霜師走',  // 和名月
  '火木金土',                        // 曜日
  '予定目標費記録習慣祝休時間第回計今前後半',
  // 祝日の名前。刷る以上は名前も要る。
  '元成人建国念天皇誕春昭和憲法海山敬老秋体育化勤労感謝振替民',
  '即位礼正殿儀喪明親王結婚太子',
  '表裏上下左右中大小新旧全部分数点合',
].join('');
const CHARSET = [...new Set(ASCII + KANA + KANJI)].join('');

const css = await get(
  `https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400&text=${encodeURIComponent(CHARSET)}`,
  // An ancient browser is offered TrueType; a modern one gets woff2, which
  // pdf-lib cannot read.
  { 'user-agent': 'Mozilla/4.0' },
);
const url = /url\((https:[^)]+)\)/.exec(await css.text())?.[1];
if (!url) throw new Error('no font url in the stylesheet');

const ttf = Buffer.from(await (await get(url)).arrayBuffer());
console.log(`${CHARSET.length} characters, ${(ttf.length / 1024).toFixed(0)} KB`);

await writeFile(
  new URL('../src/lib/render/printfont.ts', import.meta.url),
  `// GENERATED by scripts/buildfont.mjs -- do not edit by hand.\n` +
  `// Noto Sans JP (SIL Open Font License 1.1), subset to the characters below.\n` +
  `export const PRINT_FONT_CHARS = ${JSON.stringify(CHARSET)};\n\n` +
  `export const PRINT_FONT_BASE64 =\n  '${ttf.toString('base64')}';\n`,
);

async function get(url, headers) {
  const res = await fetch(url, { headers });
  if (!res.ok) throw new Error(`${res.status} ${url}`);
  return res;
}
